### ISSUE TITLE
Comment in .env files

### ISSUE THREAD

**Issue by zidanomar** [gofor-little/env#24]
i got error when i use comment inside my .env files. for example, i have 2 different env configuration in one env file to switch between configuration

```
# # Case 1
# DB_HOST=db1 -> dissabled

# Case 2
DB_HOST=db2# inline comment -> db2
DB_PASSWORD="#password" # another inline comment -> #password
```
i fork this repository, make change to enable comment and update the test cases. if you think this feature is needed, i will make a pull request

**Comment by strongishllama** [comment]
Hi @zidanomar, thanks for opening an issue and spotting this bug. If you feel like creating a pull request with a hotfix, it would be much appreciated! 🙏
